consumer_key : # place your keys available on your twitter developers account page 
consumer_secret : 
access_token : 
access_token_secret : 
channelID : !!str "@example:c" # place your channelID here, example: @vlad:e
